# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Gunicorn Web App - Kazoeru

on:
  push:
    branches: 
      - master

env:
  WEBAPP_NAME: 'kazoeru-gunicorn' # Replace with the name of your Azure web app
  RESOURCE_GROUP: 'kazoeru-gunicorn'   # Replace with the name of your Resource Group

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/
  
  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: python-app
          failOnError: true

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
