name: Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Heroku'
      url: https://kazoeru.herokuapp.com
      
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: '${{secrets.HEROKU_API_KEY}}'
          heroku_app_name: kazoeru
          heroku_email: "apiit.dinesh@gmail.com"
